# basic options
title: "Home Page"
author: "Shuvayan Brahmachary"
email: "b.shuvayan@gmail.com"

# site URL config (needed so {{ ... | relative_url }} resolves correctly)
url: "https://shuvayanb.github.io"
baseurl: "/about"   # your site is published under /about

# theme & markdown
theme: minima
markdown: kramdown
kramdown:
  input: GFM

# analytics
google_analytics: "UA-227511059-1"

# nav links (these are your header tabs)
header_pages:
  - Publications/publications.md
  - Publications/explore.html  
  - Projects/projects.md
  - Projects/interactive_flow.md
  - repositories.md
  - blogs.md

# (optional) keep build clean
exclude:
  - node_modules
  - scripts
  - vendor
  - _site

include:
  - assets/flow/mesh/index.html
  - assets/flow/mesh/pack.json.gz
