# basic options
title: Home Page
author: Shuvayan Brahmachary
email: b.shuvayan@gmail.com
description: Shuvayan Brahmachary

# Build settings
markdown: kramdown
theme: minima

google_analytics: UA-227511059-1 
