s# basic options
title: Home Page
author: Shuvayan Brahmachary
email: b.shuvayan@gmail.com

# Build settings
markdown: kramdown
theme: minima

google_analytics: UA-227511059-1 

header_pages:
  - Publications/publications.md            # or Publications/publications.md if that's your path
  - Projects/projects.md
  - repositories.md
  - blogs.md 
