title: Home Page
author: Shuvayan Brahmachary
email: b.shuvayan@gmail.com

theme: minima
markdown: kramdown

plugins:
  - jekyll-scholar

scholar:
  source: _bibliography         
  bibliography: references.bib  
  style: ieee
  locale: en
  sort_by: year
  order: descending
