# basic options
title: Home Page
author: Shuvayan Brahmachary
email: b.shuvayan@gmail.com
description: Shuvayan Brahmachary

# Build settings
markdown: kramdown
theme: minima

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YHF6CQ11GV');
</script>
