title: Home Page
author: Shuvayan Brahmachary
email: b.shuvayan@gmail.com

theme: minima
markdown: kramdown

plugins:
  - jekyll-scholar

scholar:
  # Point directly to the file. No 'source' key, no nested paths.
  bibliography: _bibliography/references.bib
  style: ieee
  locale: en
  sort_by: year
  order: descending
