# basic options
title: Home Page
author: Shuvayan Brahmachary
email: b.shuvayan@gmail.com

# Build settings
markdown: kramdown
theme: minima

google_analytics: UA-227511059-1 

plugins:
  - jekyll-scholar

scholar:
  source: Publications/_bibliography
  bibliography: references.bib
  style: ieee     # or "apa" etc.
  locale: en
  sort_by: year
  order: descending
