title: Home Page
author: Shuvayan Brahmachary
email: b.shuvayan@gmail.com

theme: minima
markdown: kramdown

plugins:
  - jekyll-scholar

scholar:
  bibliography_template: bibitem
  source: _bibliography         
  bibliography: references.bib  
  style: _bibliography/ieee-with-url.csl
  locale: en
  sort_by: year
  order: descending
