name: Build Publications from BibTeX

on:
  workflow_dispatch:
  push:
    paths:
      - reference.bib
      - scripts/bib2pubs.py

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install bibtexparser pylatexenc
      - name: Generate publications
        run: |
          python scripts/bib2pubs.py
      - name: Diagnostics
        run: |
          echo "Root:"; pwd
          echo "Tree:"; ls -la
          echo "_includes:"; ls -la _includes || true
          echo "Preview file head:"
          sed -n '1,50p' _includes/publications_list.md || true
          echo "Git status:"
          git status --porcelain
      - name: Commit changes (if any) and push
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
          # 1) Stage & commit generated files FIRST
          git add -A
          git diff --cached --quiet || git commit -m "chore: update publications from BibTeX"
      
          # 2) Rebase on top of remote (safe, clean tree now)
          git pull --rebase --autostash
      
          # 3) Push
          git push

