name: Build Publications from BibTeX

on:
  workflow_dispatch:
  push:
    paths:
      - reference.bib
      - scripts/bib2pubs.py

permissions:
  contents: write  # allow committing back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (pinned)
        run: |
          pip install "bibtexparser==1.4.0" pylatexenc

      - name: Generate publications list
        run: |
          python scripts/bib2pubs.py

      - name: Diagnostics
        run: |
          echo "PWD: $(pwd)"
          echo "Root:"; ls -la
          echo "_includes:"; ls -la _includes || true
          echo "reference.bib (first 40 lines):"
          sed -n '1,40p' reference.bib || true
          echo "Generated publications_list.md (first 40 lines):"
          sed -n '1,40p' _includes/publications_list.md || true
          echo "Git status:"
          git status --porcelain

      - name: Commit changes (if any) and push
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 1) Stage & commit generated files FIRST (avoid 'unstaged changes' on pull)
          git add -A
          git diff --cached --quiet || git commit -m "chore: update publications from BibTeX"

          # 2) Rebase to remote cleanly, then push
          git pull --rebase --autostash || git pull --rebase
          git push
