name: Build Publications from BibTeX

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'Publications/references.bib'
      - 'scripts/bib2pubs.py'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: pip install "bibtexparser==1.4.0"

      - name: Sanity: show bib head
        run: |
          ls -la Publications || true
          echo "---- head of Publications/references.bib ----"
          head -n 40 Publications/references.bib || true

      - name: Generate publications.md
        run: |
          python scripts/bib2pubs.py
          echo "---- head of Publications/publications.md ----"
          sed -n '1,160p' Publications/publications.md || true
          echo "---- check preprint key ----"
          grep -n "menonscientific" Publications/publications.md || true

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Publications/publications.md assets/data/pubs.json || true
          git commit -m "chore: regenerate Publications page" || echo "Nothing to commit"
          git pull --rebase --autostash || true
          git push || true
