name: Build Publications from BibTeX

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - '**/*.bib'
      - 'scripts/bib2pubs.py'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: pip install "bibtexparser==1.4.0" pylatexenc PyYAML

      - name: Sanity: show bib head
        run: |
          echo "Working dir: $(pwd)"
          ls -la
          ls -la _bibliography || true
          ls -la Publications || true
          echo "---- head of references.bib ----"
          head -n 30 _bibliography/references.bib || head -n 30 Publications/references.bib || true

      - name: Generate Publications page
        run: |
          python scripts/bib2pubs.py
          echo "---- head of generated Publications/publications.md ----"
          sed -n '1,160p' Publications/publications.md || true
          echo "---- grep menonscientific ----"
          grep -n "menonscientific" Publications/publications.md || true

      - name: Commit changes (if any) and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Publications/publications.md assets/data/*.json || true
          git commit -m "chore(bib2pubs): regenerate Publications" || echo "Nothing to commit"
          git pull --rebase --autostash || true
          git push || true
