name: Build Publications from BibTeX

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]   # your default will be one of these
    paths:
      - '**/*.bib'
      - 'scripts/bib2pubs.py'
      - 'Publications/**'
      
permissions:
  contents: write  # allow committing back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install bibtexparser networkx python-louvain
      
      - name: Build publications & graph (with debug)
        env:
          DEBUG_BIB2PUBS: "1"
        run: |
          python scripts/bib2pubs.py
          echo "----- pubs.json head -----"
          head -n 40 assets/data/pubs.json || true
          echo "----- topic_graph.json head -----"
          head -n 60 assets/data/topic_graph.json || true

          
      - name: Install deps (pinned)
        run: |
          pip install "bibtexparser==1.4.0" pylatexenc PyYAML

      - name: Generate Publications page
        run: |
          python scripts/bib2pubs.py

      - name: Diagnostics
        run: |
          echo "PWD: $(pwd)"
          echo "Root:"; ls -la
          echo "Publications dir:"; ls -la Publications || true
          echo "Bib files found:"; ls -la **/*.bib || true
          echo "First 40 lines of chosen bib (if any):"
          if [ -f .bib2pubs_last_bib.txt ]; then cat .bib2pubs_last_bib.txt; fi
          echo "Generated Publications/publications.md (first 80 lines):"
          sed -n '1,80p' Publications/publications.md || true
          echo "Git status:"
          git status --porcelain

      - name: Commit changes (if any) and push
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: regenerate Publications/publications.md" || echo "Nothing to commit"
          git pull --rebase --autostash || true
          git push || true
