name: Build Publications from BibTeX

on:
  workflow_dispatch:
  push:
    paths:
      - reference.bib
      - scripts/bib2pubs.py

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install bibtexparser pylatexenc
      - name: Generate publications
        run: |
          python scripts/bib2pubs.py
      - name: Commit changes (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add -A
          git diff --cached --quiet || git commit -m "chore: update publications from BibTeX"
          git push
